language: cpp
sudo: false

addons:
  coverity_scan:
    project:
      name: "diydrones/ardupilot"
      description: "Build submitted via Travis CI"
    notification_email: andrew-scan@tridgell.net
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: coverity_scan
    
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
      - llvm-toolchain-precise-3.7
    packages:
      - build-essential
      - gawk
      - ccache
      - genromfs
      - libc6-i386
      - python-pip
      - python-dev
      - zlib1g-dev
      - gcc-4.9
      - g++-4.9
      - cmake
      - cmake-data
      - clang-3.7
      - llvm-3.7

cache:
  ccache: true
  directories:
    - $HOME/.cache/pip
    - $HOME/opt

before_install:
  - Tools/scripts/configure-ci.sh

script:
  - python Tools/autotest/param_metadata/param_parse.py
  - Tools/scripts/build_ci.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e5e0b55e353e53945b4b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "FjIwqZQV2FhNPWYITX5LZXTE38yYqBaQdbm3QmbEg/30wnPTm1ZOLIU7o/aSvX615ImR8kHoryvFPDQDWc6wWfqTEs3Ytq2kIvcIJS2Y5l/0PFfpWJoH5gRd6hDThnoi+1oVMLvj1+bhn4yFlCCQ2vT/jxoGfiQqqgvHtv4fLzI="

# Note: while https://github.com/travis-ci/travis-ci/issues/4393 isn't solved we need to hack compiler name to have cache work properly

matrix:
  include:
    - compiler: "gcc PX4"
      env: CI_BUILD_TARGET="px4-v2 px4-v4"
    - compiler: "gcc Native"
      env: CI_BUILD_TARGET="sitl linux minlure"
    - compiler: "gcc Linux"
      env: CI_BUILD_TARGET="navio raspilot bebop"
    - compiler: "gcc SITL Test"
      env: CI_BUILD_TARGET="sitltest"
    - compiler: "clang Native"
      env: CI_BUILD_TARGET="sitl linux minlure"
    - compiler: "clang Linux"
      env: CI_BUILD_TARGET="navio raspilot bebop"
